###

GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Marcos Lindo",
    "email": "marcos@gmail.com",
    "password": "123",
    "profile": "ADM"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "marcos@gmail.com",
    "password": "123"
}

###

GET http://localhost:3000/issues

###
POST http://localhost:3000/issues
Content-Type: application/json

{
    "title": "Deu bug",
    "description": "não consigo fazer login",
    "responsible": "Marcos",
    "status": "open",
    "observations": ""
}
